repos:
  - repo: https://github.com/navaneethreddydevops/MyCustomcloud-Terraform
    rev: 0.1.1 # Get the latest from: https://github.com/gruntwork-io/pre-commit/releases
    hooks:
      - id: terraform-fmt
      - id: terraform-validate
      - id: tflint
      - id: shellcheck
