pipeline {
    agent any 
    stages {
        stage('Checking Applications Versions') {
            steps {
                sh '''
                echo 'Applications Version'
                /usr/local/bin/aws --version
                /usr/local/bin/terraform --version
                /usr/local/bin/docker --version
                '''
            }
        }
        stage('Terraform Init') {
            steps {
                echo 'Planning the West VPC'
                sh '''
                cd $WORKSPACE/Multi-Tier/terraform
                ls -lrt
                /usr/local/bin/terraform init
                '''
            }
        }
        stage('Infrastructure Plan') {
            steps {
                echo 'Creating the West VPC'
                sh '''
                cd $WORKSPACE/Multi-Tier/terraform
                ls -lrt
                /usr/local/bin/terraform plan
                '''
            }
            stage('Infrastructure Plan') {
            steps {
                echo 'Creating the West VPC'
                sh '''
                cd $WORKSPACE/Multi-Tier/terraform
                ls -lrt
                /usr/local/bin/terraform apply
                '''
            }
        }
    }
}