pipeline {
    agent any 
    stages {
        stage('Checking Applications Versions') {
            steps {
                sh '''
                echo 'Applications Version'
                /usr/local/bin/aws --version
                /usr/local/bin/terraform --version
                /usr/local/bin/docker --version
                '''
            }
        }
        stage('Infrastructure Plan') {
            steps {
                echo 'Planning the West VPC'
                sh '''
                pwd
                /usr/local/bin/terraform plan
                '''
            }
        }
        stage('Infrastructure Provisionig') {
            steps {
                echo 'Creating the West VPC'
                sh '''
                /usr/local/bin/terraform apply
                '''
            }
        }
    }
}